version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
  #   volumes:
  #     - database:/var/lib/mysql
  
  # volumes:
  #   database: